[tool.poetry]
name = "calendar_hours"
version = "0.1.0"
description = ""
authors = ["Arturo Mejia <amejia@nuxeo.com>"]

[tool.poetry.dependencies]
python = "^3.8"
icalevents = "^0.1.25"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
